### ISSUE TITLE
Get existing tests running on Python 3

### ISSUE THREAD

**Issue by simonw** [simonw/tikibar#1]

**Comment by simonw** [comment]
```
tikibar $ python3 runtests.py 
Creating test database for alias 'default'...
Traceback (most recent call last):
...
  File "/Users/simonw/Dropbox/Development/tikibar/tikibar/urls.py", line 2, in <module>
    from tikibar import views
  File "/Users/simonw/Dropbox/Development/tikibar/tikibar/views.py", line 32
    raise Http404, 'Tikibar is turned off'
                 ^
SyntaxError: invalid syntax
tikibar $ 
```

**Comment by simonw** [comment]
Fixed by https://github.com/simonw/tikibar/commit/fa62714f8b4c43e2383c2eb8e511e2cc775359df
